services:
  build:
    image: ubuntu:latest
    command: sleep infinity
    # inoder to entry in the container
    stdin_open: true
    tty: true
    volumes: 
      - ${HW_PATH}/hello_world.sh:/hello_world.sh
